#pragma once

#include "Convenience.h"

#define INSCRIPTION_BINARY_SERIALIZE_FUNCTION_DECLARE                   \
INSCRIPTION_SERIALIZE_FUNCTION_DECLARE(::Inscription::BinaryScribe);

#define INSCRIPTION_BINARY_SERIALIZE_FUNCTION_DEFINE(type)                \
INSCRIPTION_SERIALIZE_FUNCTION_DEFINE(type, ::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_INSCRIPTER_DECLARE_TABLE                 \
INSCRIPTION_INSCRIPTER_DECLARE_TABLE(::Inscription::BinaryScribe);

#define INSCRIPTION_BINARY_INSCRIPTER_DEFINE_TABLE(type)                \
INSCRIPTION_INSCRIPTER_DEFINE_TABLE(type, ::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_INSCRIPTER_TABLE                 \
INSCRIPTION_INSCRIPTER_TABLE(::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_INSCRIPTER_DECLARE_SERIALIZE_FUNCTION                \
INSCRIPTION_INSCRIPTER_DECLARE_SERIALIZE_FUNCTION(::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_INSCRIPTER_DEFINE_SERIALIZE_FUNCTION(type)                \
INSCRIPTION_INSCRIPTER_DEFINE_SERIALIZE_FUNCTION(type, ::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_INSCRIPTER_SERIALIZE_FUNCTION                \
INSCRIPTION_INSCRIPTER_SERIALIZE_FUNCTION(::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_INSCRIPTER_CREATE_TABLE  \
INSCRIPTION_INSCRIPTER_CREATE_TABLE(::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_DECLARE_CLASS_NAME_RESOLVER              \
INSCRIPTION_DECLARE_CLASS_NAME_RESOLVER(::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_DEFINE_CLASS_NAME_RESOLVER(type)         \
INSCRIPTION_DEFINE_CLASS_NAME_RESOLVER(::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_CLASS_NAME_RESOLVER              \
INSCRIPTION_CLASS_NAME_RESOLVER(::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_DEFINE_SIMPLE_CLASS_NAME_RESOLVER(type, defaultName)                 \
INSCRIPTION_DEFINE_SIMPLE_CLASS_NAME_RESOLVER(type, defaultName, ::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_TABLE_CONSTRUCTOR_DECLARE(type)                  \
INSCRIPTION_TABLE_CONSTRUCTOR_DECLARE(type, ::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_TABLE_CONSTRUCTOR_DEFINE(type)               \
INSCRIPTION_TABLE_CONSTRUCTOR_DEFINE(type, ::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_TABLE_CONSTRUCTOR_DEFINE_TEMPLATE(type, realType)                  \
INSCRIPTION_TABLE_CONSTRUCTOR_DEFINE_TEMPLATE(type, realType, ::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_TABLE_CONSTRUCTOR(type)              \
INSCRIPTION_TABLE_CONSTRUCTOR(type, ::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_INSCRIPTER_DEFINE_CONSTRUCT_FUNCTION(type)               \
INSCRIPTION_INSCRIPTER_DEFINE_CONSTRUCT_FUNCTION(type, ::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_INSCRIPTER_DECLARE_CONSTRUCT_OBJECT_FUNCTION                 \
INSCRIPTION_INSCRIPTER_DECLARE_CONSTRUCT_OBJECT_FUNCTION(::Inscription::BinaryScribe)

#define INSCRIPTION_BINARY_INSCRIPTER_DEFINE_CONSTRUCT_OBJECT_FUNCTION(type)                \
INSCRIPTION_INSCRIPTER_DEFINE_CONSTRUCT_OBJECT_FUNCTION(type, ::Inscription::BinaryScribe)